import {
  ArrowClockwise,
  ArrowSquareLeft,
  ArrowSquareRight,
  CaretDoubleRight,
  CaretDown,
  CaretRight,
  Check,
  CloudArrowUp,
  CornersOut,
  DotsSixVertical,
  DotsThreeOutline,
  FileImage,
  FileMinus,
  FolderSimplePlus,
  HandsClapping,
  Image,
  Info,
  List,
  MagnifyingGlass,
  Plus,
  Question,
  SignOut,
  Spinner,
  TagSimple,
  Toolbox,
  Trash,
  Upload,
  Warning,
  WarningCircle,
  XCircle,
} from "@phosphor-icons/react";

export {
  Upload as UploadIcon,
  Image as ImageIcon,
  FileImage as FileImageIcon,
  FileMinus as RemoveIcon,
  Trash as DeleteIcon,
  Plus as PlusIcon,
  Check as TickIcon,
  Spinner as SpinnerIcon,
  Warning as AlertIcon,
  WarningCircle as ErrorIcon,
  Check as SuccessIcon,
  MagnifyingGlass as SearchIcon,
  DotsThreeOutline as ComponentMenuIcon,
  DotsSixVertical as GrabHandleIcon,
  Info as InfoIcon,
  FolderSimplePlus as AddFirstAlbumIcon,
  CaretDoubleRight as GoToPageIcon,
  CornersOut as ExpandIcon,
  CaretDown as CaretDownIcon,
  HandsClapping as LikeIcon,
  ArrowSquareLeft as CycleLeftIcon,
  ArrowSquareRight as CycleRightIcon,
  CaretRight as CaretRightIcon,
  Question as HelpIcon,
  List as MainMenuIcon,
  SignOut as SignOutIcon,
  Toolbox as UnderConstructionIcon,
  TagSimple as TagIcon,
  XCircle as XCircleIcon,
  CloudArrowUp as DeployIcon,
  ArrowClockwise as RefreshIcon,
};
