import {
  Upload,
  Image,
  FileImage,
  FileMinus,
  Trash,
  Plus,
  Check,
  Spinner,
  Warning,
  WarningCircle,
  MagnifyingGlass,
  DotsThreeOutline,
  DotsSixVertical,
  Info,
  FolderSimplePlus,
  CaretDoubleRight,
} from "phosphor-react";

export {
  Upload as UploadIcon,
  Image as ImageIcon,
  FileImage as FileImageIcon,
  FileMinus as RemoveIcon,
  Trash as DeleteIcon,
  Plus as PlusIcon,
  Check as TickIcon,
  Spinner as SpinnerIcon,
  Warning as AlertIcon,
  WarningCircle as ErrorIcon,
  Check as SuccessIcon,
  MagnifyingGlass as SearchIcon,
  DotsThreeOutline as MenuIcon,
  DotsSixVertical as GrabHandleIcon,
  Info as InfoIcon,
  FolderSimplePlus as AddFirstAlbumIcon,
  CaretDoubleRight as GoToPageIcon,
};
